= Spatial Data on the Web Best Practice:  2021/2022 revision

Thoughts on including mention of FAIR Principles

Peter Parslow, December 2021

Some resources, linked at
https://github.com/w3c/sdw/issues/1290#issuecomment-993701139[[SDW Best
Practices Update: Add FAIR principles to the document · Issue #1290 ·
w3c/sdw (github.com)]

Idea: scatter references through the Best Practice, as well as having a
section that draws bits together

== BP 1 Introduction 

https://w3c.github.io/sdw/bp/#intro[Spatial Data on the Web Best
Practices (w3c.github.io)]

Add

“Following these guidelines should result in your data fitting more with
the FAIR Principles.”

== BP 3 Scope

https://w3c.github.io/sdw/bp/#scope[Spatial Data on the Web Best
Practices (w3c.github.io)]

Add new sub-section

=== 3.x FAIR Principles

The FAIR Principles are described at
https://www.go-fair.org/fair-principles/[FAIR Principles - GO FAIR
(go-fair.org)]; they are widely adopted (or at least aimed for) when
publishing scientific data including environmental and earth observation
data. Although the FAIR principles concentrate on machine readable data,
whilst these best practices also cover “data for humans”, there is a lot
of overlap between the FAIR Principles and the best practices described
in this paper. 

Similarly, although not currently expressed in terms of the FAIR Principles, the https://www.w3.org/TR/dwbp/[Data on the Web Best Practices] are also designed to make it easier for "data consumers to find, use and link to the data".

There have also been some suggestions for
improvement on the FAIR principles, and these are also discussed in this
section.

==== Findable

https://www.go-fair.org/fair-principles/fair-data-principles-explained/f1-meta-data-assigned-globally-unique-persistent-identifiers/[F1.
(Meta)data are assigned a globally unique and persistent identifier] is
partially fulfilled by Best Practice 1

https://www.go-fair.org/fair-principles/fair-data-principles-explained/f2-data-described-rich-metadata/[F2.
Data are described with rich metadata] is a close match to Best Practice
13

https://www.go-fair.org/fair-principles/f3-metadata-clearly-explicitly-include-identifier-data-describe/[F3.
Metadata clearly and explicitly include the identifier of the data they
describe] is fulfilled by using the standard described in Best Practice
13

https://www.go-fair.org/fair-principles/f4-metadata-registered-indexed-searchable-resource/[F4.
(Meta)data are registered or indexed in a searchable resource] – the
context of these best practices is publication on the web, which is by
definition a searchable resource – which is acknowledged in F4! It is
also supported by Best Practice 2.

Taken together, following these best practice guidelines covers the F in
the FAIR Principles. It should result in it being easier for potential
users to find your data.

==== Accessible

“Once the user finds the required data, she/he/they need to know how can
they be accessed, possibly including authentication and authorisation.”

https://www.go-fair.org/fair-principles/542-2/[A1. (Meta)data are
retrievable by their identifier using a standardised communications
protocol] is satisfied by publishing the data and metadata on the web. 

See also https://www.w3.org/TR/dwbp[DWBP] Best Practice 1: _Provide Metadata_ "to help tasks such as data discovery" _(although the intended outcome focuses on 'understand the metadata' (!))_

See also https://www.w3.org/TR/dwbp[DWBP] Best Practice 17: _Provide Bulk Downlad_, Best Practice 18: _Provide Subsets for Large Datasets_

See also https://www.w3.org/TR/dwbp[DWBP] Best Practice 23: _Make data available through an API_

https://www.go-fair.org/fair-principles/a2-metadata-accessible-even-data-no-longer-available/[A2.
Metadata are accessible, even when the data are no longer available] –
this is not covered in this best practice (because once the data is not
available on the web, this BP no longer applies?)

==== Interoperable

https://www.go-fair.org/fair-principles/i1-metadata-use-formal-accessible-shared-broadly-applicable-language-knowledge-representation/[*I1*.
(Meta)data use a formal, accessible, shared, and broadly applicable
language for knowledge representation.]

This covers (minimally) data formats, for which see Best Practice 4
(DWBP 14), but also commonly used controlled vocabularies and “a good
data model”. (_Is there a SDWBP/DWBP for this? There is a little bit
about vocabs for the geometry, and some of the metadata standards allow
reference to vocab & data model)_

https://www.go-fair.org/fair-principles/i2-metadata-use-vocabularies-follow-fair-principles/[*I2*.
(Meta)data use vocabularies that follow FAIR principles]

https://www.go-fair.org/fair-principles/i3-metadata-include-qualified-references-metadata/[*I3*.
(Meta)data include qualified references to other (meta)data] is similar
to Best Practice 3 and Best Practice 10.

==== Reusable

https://www.go-fair.org/fair-principles/r1-metadata-richly-described-plurality-accurate-relevant-attributes/[R1.
(Meta)data are richly described with a plurality of accurate and relevant attributes]

See https://www.w3.org/TR/dwbp[DWBP] Best Practice 3: _Provide structural metadata_, which doesn't require the attibution to be 'richly described' or for there to be many attributes (let alone that they be accurate & relevant); but it does at least say that whatever attribution you do provide should be described.

See https://www.w3.org/TR/dwbp[DWBP] Best Practice 31: _Enrich data by generating new data_

https://www.go-fair.org/fair-principles/r1-1-metadata-released-clear-accessible-data-usage-license/[R1.1.
(Meta)data are released with a clear and accessible data usage license]

https://www.w3.org/TR/dwbp[DWBP] Best Practice 4: _Provide data license information_; again, this doesn't say that the license should be "clear", but it does say that it should be accesible - "attached to data" (via a link from the metadata or embedded in the metadata).

https://www.go-fair.org/fair-principles/r1-2-metadata-associated-detailed-provenance/[R1.2.
(Meta)data are associated with detailed provenance]

https://www.w3.org/TR/dwbp[DWBP] Best Practice 5: _Provide data provenance information_ "Provide complete information about the origins of the data and any changes you have made."

https://www.go-fair.org/fair-principles/r1-3-metadata-meet-domain-relevant-community-standards/[R1.3.
(Meta)data meet domain-relevant community standards]

See https://www.w3.org/TR/dwbp[DWBP] Best Practice 12: _Use machine-readable standardized data formats_ "Make data available in a machine-readable, standardized data format that is well suited to its intended or potential use." This addresses the "low level", data format, aspect of (community) standards

https://www.w3.org/TR/dwbp[DWBP] Best Practice 15: _Reuse vocabularies, preferably standardized ones_ "Use terms from shared vocabularies, preferably standardized ones, to encode data and metadata." This addresses more of the semantic standardization that exists in some community standards: "Use of vocabularies already in use by others captures and facilitates consensus in communities."

_I’m not so sure of the match(es) here_

==== FAIR Challenges/extensions

A – human accessibility

The crawlers that search engine providers use to index the web are
trained to look for human readable information. So the more “human
readable” your metadata is, the more likely you are to be found in web
searches – whether by humans or machines.

When publishing data on the web, take account of web accessibility
guidelines. It is currently challenging to make web visualisations of
geospatial data accessible to assistive technology. _“Maps on the Web”
is looking at this?_

Q – quality

No matter how easy it is to find, access, and even use your data, it is
of little use unless it is of sufficient quality for the user’s task.
However, what is “good” for one task is not necessarily “good” for
another.

There are a variety of approaches in use to try to match users with data
that will be useful to them. These range from telling the user a lot
about the quality of the data to telling them what you (& others) have
successfully used it for.

https://www.w3.org/TR/dwbp[DWBP] Best Practice 6: _Provide data quality information_

Often includes https://www.w3.org/TR/dwbp[DWBP] Best Practice 21: _Provide data up to date_

